apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 725506140458.dkr.ecr.ap-south-1.amazonaws.com/nodejs-demo:IMAGE_TAG
          ports:
            - containerPort: 3000
